# Generated by Django 2.2.4 on 2022-02-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubc', '0010_auto_20220220_1452'),
        ('prd', '0002_auto_20220216_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Secciones'),
        ),
    ]
