# Generated by Django 2.2.4 on 2022-02-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubc', '0010_auto_20220220_1452'),
        ('prd', '0003_productos_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='bodega',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Bodegas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='seccion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Secciones'),
        ),
    ]
