# Generated by Django 2.2.4 on 2022-02-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0004_auto_20220226_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Bodegas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Secciones'),
        ),
    ]
