# Generated by Django 2.2.4 on 2022-02-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prv', '0003_auto_20220225_2055'),
        ('prd', '0006_auto_20220226_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prv.Proveedores'),
        ),
    ]
