# Generated by Django 2.2.4 on 2022-07-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0008_auto_20220226_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
    ]
