# Generated by Django 2.2.4 on 2022-08-31 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0009_remove_productos_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'permissions': {('editar_producto', 'Editar Prducto'), ('solicitar_producto', 'Solicitar Producto a Proveedores'), ('actualizar_producto', 'Actualizar Prducto'), ('crear_producto', 'Crear Producto')}},
        ),
    ]
