# Generated by Django 2.2.4 on 2022-02-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prv', '0002_auto_20220214_0354'),
        ('prd', '0003_productos_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPedido',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('proveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prv.Proveedores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosSolicitud',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prd.Productos')),
                ('solicitud', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trn.SolicitudPedido')),
            ],
            options={
                'permissions': {('crear_producto_pedido', 'Agregar Producto a Pedido'), ('editar_producto_pedido', 'Editar Producto a Pedido')},
            },
        ),
    ]
