# Generated by Django 2.2.4 on 2022-02-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpedido',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prv.Proveedores'),
        ),
    ]
