# Generated by Django 2.2.4 on 2022-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0003_auto_20220223_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='secuencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
