# Generated by Django 2.2.4 on 2022-02-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('trn', '0004_solicitudpedido_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
    ]
