# Generated by Django 2.2.4 on 2022-02-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prd', '0003_productos_seccion'),
        ('trn', '0005_solicitudpedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrdenBodega',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenBodega',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trn.SolicitudPedido')),
                ('tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trn.TipoOrdenBodega')),
            ],
            options={
                'permissions': {('crear_orden_ingreso', 'Agregar Orden de Ingreso'), ('ver_orden_ingreso', 'Ver Orden de Ingreso'), ('actualizar_orden_ingreso', 'Actualizar Orden de Ingreso')},
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenBodega',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trn.OrdenBodega')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prd.Productos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
