# Generated by Django 2.2.4 on 2022-03-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0007_ordenbodega_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpedido',
            name='total_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
