# Generated by Django 2.2.4 on 2022-03-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0008_solicitudpedido_total_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpedido',
            name='total_envio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
