# Generated by Django 2.2.4 on 2022-03-07 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prd', '0008_auto_20220226_2122'),
        ('bases', '0002_configuracionsistema'),
        ('trn', '0009_auto_20220228_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('secuencia', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_almacenado', models.DateTimeField(blank=True, null=True)),
                ('total_orden', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
            options={
                'permissions': {('crear_orden_produccion', 'Agregar Orden Produccion'), ('editar_orden_produccion', 'Editar Orden Produccion')},
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trn.OrdenProduccion')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prd.Productos')),
            ],
            options={
                'permissions': {('crear_producto_orden', 'Agregar Producto a Orden'), ('editar_producto_orden', 'Editar Producto a Orden')},
            },
        ),
    ]
