# Generated by Django 2.2.4 on 2022-03-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0010_detalleorden_ordenproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenbodega',
            name='orden_produccion',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
