# Generated by Django 2.2.4 on 2022-03-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0011_ordenbodega_orden_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenbodega',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trn.SolicitudPedido'),
        ),
    ]
