# Generated by Django 2.2.4 on 2022-07-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0012_auto_20220308_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudpedido',
            options={'permissions': {('ver_ordenes_proveedor', 'Ver ordenes de Proveedores'), ('crear_orden_proveedor', 'Crear Orden a Proveedores')}},
        ),
    ]
