# Generated by Django 2.2.4 on 2022-07-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0013_auto_20220711_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudpedido',
            options={'permissions': {('ver_ordenes_proveedor', 'Ver ordenes de Proveedores'), ('actualizar_ordenes_proveedor', 'Actualizar ordenes de Proveedores'), ('crear_orden_proveedor', 'Crear Orden a Proveedores'), ('editar_ordenes_proveedor', 'Editar ordenes de Proveedores')}},
        ),
    ]
