# Generated by Django 2.2.4 on 2022-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0016_auto_20220717_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='usuario_despacha_pedido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='usuario_recibe_pedido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
