# Generated by Django 2.1 on 2022-01-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('ubc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
        ),
        migrations.AddField(
            model_name='pais',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciudades',
            name='pais',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Pais'),
        ),
    ]
