# Generated by Django 2.1 on 2022-01-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubc', '0002_auto_20220124_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
    ]
