# Generated by Django 2.2.4 on 2022-02-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('ubc', '0003_auto_20220124_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Ciudades')),
                ('estado', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('estado', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('sector', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Sectores')),
            ],
        ),
    ]
