# Generated by Django 2.2.4 on 2022-02-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubc', '0007_pais_prefijo_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudades',
            name='codigo_api_ciudad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
