# Generated by Django 2.2.4 on 2022-02-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubc', '0008_ciudades_codigo_api_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('direccion1', models.CharField(max_length=150)),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Ciudades')),
            ],
            options={
                'permissions': {('crear_bodega', 'Crear Bodega'), ('editar_bodega', 'Editar Bodega'), ('actualizar_bodega', 'Actualizar Bodega')},
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('bodega', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Bodegas')),
            ],
            options={
                'permissions': {('crear_bodega', 'Crear Bodega'), ('editar_bodega', 'Editar Bodega'), ('actualizar_bodega', 'Actualizar Bodega')},
            },
        ),
    ]
