# Generated by Django 2.2.4 on 2022-02-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('ubc', '0009_bodegas_secciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegas',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
        migrations.AddField(
            model_name='secciones',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
    ]
