# Generated by Django 2.2.4 on 2022-03-03 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('trn', '0009_auto_20220228_2151'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('vista', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField(blank=True, null=True)),
                ('encargado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('orden', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trn.OrdenBodega')),
            ],
        ),
    ]
