# Generated by Django 2.2.4 on 2022-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='orden_prd',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
