# Generated by Django 2.2.4 on 2022-03-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntf', '0002_notificacion_orden_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trn.OrdenBodega'),
        ),
    ]
