# Generated by Django 2.2.4 on 2022-07-12 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntf', '0005_notificacion_proveedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
