# Generated by Django 2.1 on 2022-01-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFinca',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=350)),
                ('segundo_nombre', models.CharField(max_length=350)),
                ('primer_apellido', models.CharField(max_length=350)),
                ('segundo_apellido', models.CharField(max_length=350)),
                ('direccion', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
