# Generated by Django 2.2.4 on 2022-02-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('personal', '0003_auto_20220207_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=350)),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
            options={
                'permissions': {('crear_categoria_proveedor', 'Crear Categoria Proveedor'), ('editar_categoria_proveedor', 'Editar Categoria Proveedor'), ('actualizar_categoria_proveedor', 'Actualizar Categoria Proveedor')},
            },
        ),
        migrations.AlterModelOptions(
            name='personalfinca',
            options={'permissions': {('crear_personal', 'Crear Personal'), ('editar_personal', 'Editar Personal'), ('actualizar_personal', 'Actualizar Personal')}},
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=350)),
                ('segundo_nombre', models.CharField(max_length=350)),
                ('primer_apellido', models.CharField(max_length=350)),
                ('segundo_apellido', models.CharField(max_length=350)),
                ('direccion', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=15)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.CategoriaProveedor')),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
            options={
                'permissions': {('editar_proveedor', 'Editar Proveedor'), ('crear_proveedor', 'Crear Proveedor'), ('actualizar_proveedor', 'Actualizar Proveedor')},
            },
        ),
    ]
