# Generated by Django 2.2.4 on 2022-02-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20220211_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='estado',
        ),
        migrations.DeleteModel(
            name='CategoriaProveedor',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
