# Generated by Django 2.2.4 on 2022-08-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20220214_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalFinca',
        ),
    ]
