# Generated by Django 2.2.4 on 2022-08-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20220804_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapersonal',
            name='usuario_crea',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalfinca',
            name='usuario_crea',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipopersonal',
            name='usuario_crea',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
