# Generated by Django 2.2.4 on 2022-02-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('ubc', '0008_ciudades_codigo_api_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, null=True, unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Ciudades')),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_prv', to='bases.Estados')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Pais')),
            ],
            options={
                'permissions': {('editar_proveedor', 'Editar Proveedor '), ('crear_proveedor', 'Crear Proveedor   '), ('actualizar_proveedor', 'Actualizar Proveedor ')},
            },
        ),
    ]
