# Generated by Django 2.2.4 on 2022-02-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'permissions': {('editar_proveedor', 'Editar Proveedor'), ('crear_proveedor', 'Crear Proveedor'), ('actualizar_proveedor', 'Actualizar Proveedor')}},
        ),
    ]
