# Generated by Django 2.2.4 on 2022-02-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_configuracionsistema'),
        ('prv', '0002_auto_20220214_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proveedores',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prv.CategoriaProveedor'),
        ),
    ]
