# Generated by Django 2.2.4 on 2022-07-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prv', '0003_auto_20220225_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='categoria',
        ),
        migrations.CreateModel(
            name='CategoriasProveedor',
            fields=[
                ('id_categoria_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prv.CategoriaProveedor')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prv.Proveedores')),
            ],
        ),
    ]
