# Generated by Django 2.2.4 on 2022-07-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prv', '0005_proveedores_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='usuario',
        ),
    ]
