# Generated by Django 2.2.4 on 2022-08-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prv', '0007_proveedores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasproveedor',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_proveedor', to='prv.Proveedores'),
        ),
    ]
