# Generated by Django 2.2.4 on 2022-02-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'permissions': {('editar_rol', 'Ediatr Rol'), ('crear_rol', 'Crear Rol'), ('actualizar_rol', 'Actualizar Rol')}},
        ),
    ]
