# Generated by Django 2.2.4 on 2022-02-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_auto_20220207_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_img'),
        ),
    ]
