# Generated by Django 2.2.4 on 2022-02-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0004_usuarios_img_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
