# Generated by Django 2.2.4 on 2022-02-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0005_usuarios_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='usuario_telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
