# Generated by Django 2.2.4 on 2022-02-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0006_usuarios_usuario_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosGrupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usr_usuarios_groups',
                'managed': False,
            },
        ),
    ]
