# Generated by Django 2.2.4 on 2022-02-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0007_usuariosgrupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True)),
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
