# Generated by Django 2.2.4 on 2022-02-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0008_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usr.TipoUsuario'),
        ),
    ]
